cdcollsale/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cdcollectionsale/', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))

main/urls.py
from django.urls import path

from .views import index, other_pages, profile, cart, CDLoginView, CDLogoutView, ChangeUserInfoView,\
    ChangePasswordView, RegisterUserView, RegisterDoneView, user_activate, DeleteUserView, band_view, item_view

app_name = 'main'
urlpatterns = [
    path('band/<slug:band_slug>/', band_view, name='band'),
    path('item/<int:pk>/', item_view, name='item'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/activate/<str:sign>/', user_activate, name='register_activate'),
    path('accounts/login/', CDLoginView.as_view(), name='login'),
    path('accounts/logout/', CDLogoutView.as_view(), name='logout'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
    path('accounts/profile/password_change/', ChangePasswordView.as_view(), name='password_change'),
    path('accounts/cart/', cart, name='cart'),
    path('', index, name='index'),
    path('<str:page>/', other_pages, name='other'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class BuyerUser(AbstractUser):
    is_activated = models.BooleanField(default=True, db_index=True, verbose_name='Активирован')
    send_notif = models.BooleanField(default=True, db_index=True, verbose_name='Посылать уведомления')

    class Meta(AbstractUser.Meta):
        pass


class Artist(models.Model):
    name = models.CharField(max_length=64, verbose_name='Исполнитель')
    country = models.CharField(max_length=32, null=True, blank=True, verbose_name='Страна')
    slug = models.SlugField(max_length=64, null=True, blank=True, db_index=True,
                            verbose_name='URL')

    class Meta:
        verbose_name = 'Исполнитель'
        verbose_name_plural = 'Исполнители'
        ordering = ['name']

    def __str__(self):
        return self.name


class ItemType(models.Model):
    class Types(models.TextChoices):
        CD = 'CD', 'CD'
        DOUBLE_CD = '2xCD', '2xCD'
        CD_DIGIPAK = 'CD Digipak', 'CD Digipak'
        DOUBLE_CD_DIGIPAK = '2xCD Digipak', '2xCD Digipak'
        DVD = 'DVD', 'DVD'
        DOUBLE_DVD = '2xDVD', '2xDVD'
        DVD_DIGIPAK = 'DVD Digipak', 'DVD Digipak'
        DOUBLE_DVD_DIGIPAK = '2xDVD Digipak', '2xDVD Digipak'
    format = models.CharField(max_length=16, choices=Types.choices, default=Types.CD, verbose_name='Формат')

    class Meta:
        verbose_name = 'Формат'
        verbose_name_plural = 'Форматы'

    def __str__(self):
        return self.format


class Label(models.Model):
    name = models.CharField(max_length=50, verbose_name='Название')
    slug = models.SlugField(max_length=50,  null=True, blank=True, db_index=True, allow_unicode=True,
                            verbose_name='URL')

    class Meta:
        verbose_name = 'Лейбл'
        verbose_name_plural = 'Лейблы'

    def __str__(self):
        return self.name


class Item(models.Model):
    item_type = models.ForeignKey(ItemType, on_delete=models.PROTECT)
    artist = models.ForeignKey(Artist, on_delete=models.PROTECT)
    album = models.CharField(max_length=128, verbose_name='Альбом')
    slug = models.SlugField(max_length=128,  null=True, blank=True, db_index=True, allow_unicode=True,
                            verbose_name='URL')
    label = models.ForeignKey(Label, related_name='items', on_delete=models.PROTECT)
    licensed_by = models.ForeignKey(Label, null=True, blank=True, on_delete=models.PROTECT)
    year = models.CharField(max_length=4)
    license_year = models.CharField(max_length=4, null=True, blank=True)
    price = models.DecimalField(max_digits=4, decimal_places=2)
    image = models.ImageField(blank=True, null=True)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товар'
        ordering = ['-id']

    def __str__(self):
        return self.album

    def labels(self):
        if self.licensed_by:
            return '%s/%s' % (self.label, self.licensed_by)
        else:
            return self.label

main/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError

from .models import BuyerUser
from .apps import user_registered


class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Электронная почта')
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput,
                                help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label='Пароль (ещё раз)', widget=forms.PasswordInput,
                                help_text='Введите пароль ещё раз для проверки')

    def clean_password(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError('Пароли не совпадают', code='password_mismatch')}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
        user_registered.send(RegisterUserForm, instance=user)
        return user

    class Meta:
        model = BuyerUser
        fields = ('username', 'email', 'password1', 'password2',
                  'first_name', 'last_name', 'send_notif')


class ChangeUserInfoForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Электронная почта')

    class Meta:
        model = BuyerUser
        fields = ('username', 'email', 'first_name', 'last_name', 'send_notif')

main/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from django.template.loader import get_template
from django.template import TemplateDoesNotExist, RequestContext
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic.base import TemplateView
from django.core.signing import BadSignature

from .models import BuyerUser, Artist, Item
from .forms import ChangeUserInfoForm, RegisterUserForm
from .utilities import signer


class RegisterUserView(CreateView):
    model = BuyerUser
    template_name = 'main/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('main:register_done')


class RegisterDoneView(TemplateView):
    template_name = 'main/register_done.html'


def user_activate(request, sign):
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'main/bad_signature.html')
    user = get_object_or_404(BuyerUser, username=username)
    if user.is_activated:
        template = 'main/user_is_activated.html'
    else:
        template = 'main/activation_done.html'
        user.is_active = True
        user.is_activated = True
        user.save()
    return render(request, template)


class CDLoginView(LoginView):
    template_name = 'main/login.html'
    next_page = 'main:profile'


class CDLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'main/logout.html'


def index(request):
    return render(request, 'main/index.html')


def band_view(request, band_slug):
    artist = Artist.objects.get(slug=band_slug)
    return render(request, 'main/band.html', context={'artist': artist})


def item_view(request, pk):
    album = Item.objects.get(pk=pk)
    return render(request, 'main/item.html', context={'album': album})


class DeleteUserView(LoginRequiredMixin, DeleteView):
    model = BuyerUser
    template_name = 'main/delete_user.html'
    success_url = reverse_lazy('main:index')

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        logout(request)
        messages.add_message(request, messages.SUCCESS, 'Пользователь успешно удалён.')
        return super().post(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


@login_required
def profile(request):
    return render(request, 'main/profile.html')


class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = BuyerUser
    template_name = 'main/change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('main:profile')
    success_message = 'Вы успешно изменили свои данные.'

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class ChangePasswordView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = 'main/password_change.html'
    success_url = reverse_lazy('main:profile')
    success_message = 'Вы успешно изменили свой пароль.'


@login_required
def cart(request):
    return render(request, 'main/cart.html')


def other_pages(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))

main/templates/main/about.html
{% extends "main/basic.html" %}

{% block title %}О сайте{% endblock title %}

{% block content %}
<h2>CD Collecton Sale</h2>
<p>CD Collection Sale — это магазин дисков из моей коллекции.</p>
{% endblock content %}

main/templates/main/activation_done.html
{% extends 'main/basic.html' %}

{% block title %}Активация выполнена{% endblock title %}

{% block content %}

<h2>Активация</h2>
<p>Вы успешно активировали свою учётную запись!</p>
<p><a href="{% url 'main:login' %}">Войти на сайт</a></p>

{% endblock content %}

main/templates/main/bad_signature.html
{% extends 'main/basic.html' %}

{% block title %}Ошибка при активации{% endblock title %}

{% block content %}

<h2>Активация</h2>
<p>При попытке активации произошла ошибка.</p>
<p><a href="{% url 'main:register' %}">Зарегистрироваться снова</a></p>

{% endblock content %}

main/templates/main/band.html
{% extends 'main/basic.html' %}

{% block title %}{{ artist }}{% endblock title %}

{% block content %}

<div>
    <div>
        <img src="/static/main/bands/{{ artist.slug }}.jpg"
        style="width: 300px;" alt="{{ artist }}" title="{{ artist }}">
    </div>
    <div>
        {{ artist }}
    </div>
</div>

{% endblock content %}

main/templates/main/cart.html
{% extends 'main/basic.html' %}

{% block title %}Корзина{% endblock title %}

{% block content %}

<h2>Ваша корзина:</h2>

{% endblock content %}

main/templates/main/change_user_info.html
{% extends 'main/basic.html' %}

{% load bootstrap4 %}

{% block title %}Изменение личных данных{% endblock title %}

{% block content %}

<h2>Правка личных данных пользователя {{ user.username }}</h2>
<form method="POST">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Сохранить' %}{% endbuttons %}
</form>

{% endblock content %}

main/templates/main/delete_user.html
{% extends 'main/basic.html' %}

{% load bootstrap4 %}

{% block title %}Удаление пользователя{% endblock title %}

{% block content %}

<h2>Удаление пользователя {{ object.username }}</h2>
<p>Вы действительно хотите удалить свою учётную запись?</p>
<form method="POST">
    {% csrf_token %}
    {% buttons submit='Да, удалить' %}{% endbuttons %}
</form>

{% endblock content %}

main/templates/main/index.html
{% extends 'main/basic.html' %}

{% block content %}

<h2>Последние 10 дисков</h2>

<div>
    {% for album in item_list %}
    <div>
        <a href="{% url 'main:item' album.pk %}" class="list-group-item list-group-item-action">
            <img src="/static/main/covers/{{ album.pk }}.jpg"
        style="width: 300px;" alt="{{ album.artist }} — {{ album }}" title="{{ album.artist }} — {{ album }}"></a>
    </div>
    <div>
        <h6>{{ album.artist }} — {{ album }} ({{ album.year }}, {{ album.labels }})</h6>
    </div>
    {% endfor %}
</div>

{% endblock content %}

main/templates/main/item.html
{% extends 'main/basic.html' %}

{% block content %}

<div>
    <div>
        <img src="/static/main/covers/{{ album.pk }}.jpg"
        style="width: 300px;" alt="{{ album.artist }} — {{ album }}" title="{{ album.artist }} — {{ album }}">
    </div>
    <div>
        <h6>{{ album.artist }} — {{ album }} ({{ album.year }}, {{ album.labels }})</h6>
    </div>
</div>

{% endblock content %}

main/templates/main/logout.html
{% extends 'main/basic.html' %}

{% block title %}Выход{% endblock title %}

{% block content %}

<h2>Выход</h2>
<p>Вы успешно вышли из своей учётной записи.</p>

{% endblock %}

main/templates/main/profile.html
{% extends 'main/basic.html' %}

{% block title %}Профиль{% endblock title %}

{% block content %}

<h2>Профиль покупателя {{ user.username }}</h2>
<p>Здравствуйте, {{ user.first_name }} {{ user.last_name }}!</p>

<p>Ваши данные:</p>
<ul>
    <li>Имя в магазине: {{ user.username }}</li>
    <li>Имя: {{ user.first_name }}</li>
    <li>Фамилия: {{ user.last_name }}</li>
    <li>E-mail: {{ user.email }}</li>
</ul>
<p><a href="{% url 'main:cart' %}">Ваша корзина</a></p>

{% endblock content %}

main/templates/main/register_done.html
{% extends 'main/basic.html' %}

{% block title %}Регистрация завершена{% endblock title %}

{% block content %}

<h2>Регистрация</h2>
<p>Регистрация завершена</p>
<p>На указанную Вами электронную почту отправлено письмо.</p>
<p>Проверьте, пожалуйста, свой почтовый ящик и пройдите по ссылке, чтобы активировать учётную запись.</p>

{% endblock content %}

main/templates/main/register_user.html
{% extends 'main/basic.html' %}

{% load bootstrap4 %}

{% block title %}Регистрация{% endblock title %}

{% block content %}

<h2>Регистрация нового пользователя</h2>

<form method="POST">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Зарегистрироваться' %}{% endbuttons %}
</form>

{% endblock content %}

main/templates/main/user_is_activated.html
{% extends 'main/basic.html' %}

{% block title %}Пользователь уже активирован!{% endblock title %}

{% block content %}

<h2>Активация</h2>
<p>Пользователь с именем {{ request.user }} уже активирован ранее.</p>
<p><a href="{% url 'main:login' %}">Войти на сайт</a></p>

{% endblock content %}